/** Source Directory:
 * $ npx create-next-app@latest
 * Need to install the following packages:
  create-next-app@latest
 * Ok to proceed? (y) y
√ What is your project named? ... trello-appwrite-clone
√ Would you like to use TypeScript with this project? ... No / Yes
√ Would you like to use ESLint with this project? ... No / Yes
√ Would you like to use Tailwind CSS with this project? ... No / Yes
√ Would you like to use `src/` directory with this project? ... No / Yes
√ Use App Router (recommended)? ... No / Yes
√ Would you like to customize the default import alias? ... No / Yes
*/

/**
 * npm run dev
 * localhost:3000
*/

import Modal from '@/components/Modal'
import './globals.css'

export const metadata = {
  title: 'Trello 2.0 Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F8]'>
        {children}
        <Modal />
      </body>
    </html>
  )
}
